### ISSUE TITLE
Check and add translations 

### ISSUE THREAD

**Issue by NielsRoels** [Intracto/SecretSanta#110]
Over the past few weeks quiet a lot of new translations have been added to the project. English, French, Spanish and Dutch translations have all been updated to go along with the current state of the project, but should be checked on grammar and correct translations. Other languages still need to be translated.

Translations that should be checked / translated into other languages for all files:
- create
  - list_administator
  - import 
    - instructions
    - too_many_files
    - wrong_format
- manage
  - watch_out
  - modify_list
- expose_wishlists
  - title
  - body
  - phrase_to_type
- entry
  - location
  - wishlists_exposed
  - wishlists_not_exposed
  - watch_out
  - modify_list
- poke
  - poke
  - poke_sentence
- add_participant
  - title
  - body
- updated_party
  - title
  - body
- faq (will be updated in upcoming commit)
  - title
  - body
- label
  - host
  - participants
  - location
  - items
- btn
  - add_person
  - remove
  - import_persons 
    - open
    - do
  - save_item
  - update_item
  - remove_item
  - expose_wishlists
  - expose_wishlists_confirm
  - pool_update
  - add_participant
  - add_participant_confirm
  - updated_party
- emails
  - poke_buddy
    - subject
    - message
      - html
      - txt
  - pool_update
    - subject
    - message
      - html
      - txt
    - btn_pool_update
  - poolstatus
    - subject
    - message
      - html
      - txt
    - btn_poolstatus
  - admin_wishlists
    - subject
    - message
      - html
      - txt
  - updated_party
    - subject
    - message
      - html
      - txt
  - removed_secret_santa (will be added soon)
    - subject
    - message
      - html
      - txt
    - btn_find_out
- flashes
  - expose_wishlists
  - poke_buddy
  - pool_update
    - success
  - remove_participant
    - success
    - danger
    - warning
    - excluded_entries
  - add_participant
    - success
    - danger
  - wishlist
    - empty_row
    - added
    - updated
    - removed
  - updated_party  
    - success
    - danger
- report
  - title
  - results
  - analytics
  - total_overview
  - all_time
  - parties
  - participants
  - total
  - total_result
  - season
  - created_parties
  - confirmed_parties
  - confirmed_parties_month
  - confirmed_parties_total
  - invited_participants
  - confirmed_participants
  - confirmed_participants_month
  - confirmed_participants_total
  - average_entries
  - unique_entries
  - completed_wishlists
  - ip_usage
  - visitors_per_country
  - visitors_per_language
  - mobile_usage
  - top_browser
  - no_data
  - season_info
  - marketing_automation
  - mandrill_report
    - title
    - sent
    - opened
    - unique

**Comment by tvlooy** [comment]
I reviewed the current languages usage and we will keep them all. I asked the translators to do their work on the translation files.
