### ISSUE TITLE
Warn people about consequences when delete a participant

### ISSUE THREAD

**Issue by NielsRoels** [Intracto/SecretSanta#114]
Some people might have already bought a present for their Secret Santa when the admin removes them from the party. Make sure the admin is clearly notified of the consequences it may cause and make sure the participant know the admin can still add or remove people. 

Send a mail to the participants that were affected by deleting one. This way they know that things have changed and it makes sure that they know about their new Secret Santa.

Maybe add a deadline to adding/removing people, this way participants get the time to buy a present for the correct person, if they buy it after the deadline expired.

**Comment by mvanspringel** [comment]
@tvlooy Moeten hier nog wijzigingen gebeuren, of kan deze gesloten worden?

**Comment by tvlooy** [comment]
nee, we pikken dit op via #207
