### ISSUE TITLE
Excludes broken

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#122]
Voorbeeld:
http://www.secretsantaorganizer.com/exclude/nmo7fe44pa808cgcgksg0oco48s8o08#mysanta

Vroeger zag dit er anders uit (UI) en werkte het ook voor de gewone mens (UX = ctrl+click om te un-selecten?). Excludes worden volgens mij ook geweigerd.

Zie screenshot:
![exclude](https://cloud.githubusercontent.com/assets/391674/15668933/0585573c-271e-11e6-81d1-e95b1d4747e1.png)

Iemand die dit kan nakijken / fixen (eventueel eens een oude versie uitchecken om te vergelijken)? /cc @acrobat @rvanginneken @pix-art @Moskydesign

**Comment by pix-art** [comment]
Momenteel werkt dit wel, UI moet ik even controleren. Maar het is logisch dat je niemand kan weigeren momenteel. 

Als 1 niet voor 2 mag kopen moet hij voor 3 kopen, waardoor 3 automatisch voor 2 moet kopen en 2 voor 1. -> dus geen random scenario. Je kan pas vanaf 4 users mensen blockeren.

**Comment by tvlooy** [comment]
ja idd niet kunnen selecteren klopt in dit geval

met de UI is volgens mij iets gebeurd. Dit is een scherm waar iedereen voorbij moet en momenteel is het niet clean / gebruiksvriendelijk / ... genoeg. Volgens mij zag het er vroeger een stuk beter uit

**Comment by pix-art** [comment]
PR created
