### ISSUE TITLE
Knop in bevestigingsmail werkt niet

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#132]
Knop "Descubra quem é seu Amigo Secreto" heeft geen href. Mensen kunnen hun "buddy" niet zien.

**Comment by tvlooy** [comment]
fixed in 63048a8546177d8f93dbd137f40133ce50a6ae22

**Comment by pix-art** [comment]
eek, my bad it seems :o

**Comment by tvlooy** [comment]
Shit happen

**Comment by tvlooy** [comment]
s
