### ISSUE TITLE
Same People

### ISSUE THREAD

**Issue by waikariboy** [Intracto/SecretSanta#137]
Second year in a row I have used this great site, but we all good the same people this year as last year, ( I don't know who got who but I got the same person and another person told me they had there secret Santa last year also). Was to it something I done wrong?

**Comment by pix-art** [comment]
The algorithm as shown below uses the shuffle function, so it should be random. May I ask how many people were in your pool? Because if it's only like 3 or 4 the chance of getting the same people is substantially higher than when you have 10 people in your pool.

```
    /**
     * @param $list
     *
     * @return mixed
     */
    private function shuffleArray($list)
    {
        shuffle($list);
        return $list;
    }
```

**Comment by tvlooy** [comment]
@waikariboy I think the best thing to do is you send us an email with your pool id / management page to info@secretsantaorganizer.com so we can find out who you are and take a look at the issue

**Comment by tvlooy** [comment]
closed because this seems to be not a code issue

**Comment by waikariboy** [comment]
6 of us, done again, but used the part were you can select people not to get someone. Worked fine this time.

**Comment by tvlooy** [comment]
@waikariboy could you send us your list URL or admin email address? (to info@secretsantaorganizer.com) we would like to take a look at this possible bug but would like to investigate your exact case first
