### ISSUE TITLE
exports werken niet

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#138]
"./app/console intracto:exportmails" werkt niet omwille van allerhande problemen:
- directory rechten (mysql user heeft geen schrijf rechten op onze documentroot)
- mysql --secure-file-priv (mag niet eens files schrijven in die direcotry)
- sql_mode=only_full_group_by (velden van select zitten niet in group by, query klopt niet)

dat moet iemand nakijken en fixen. Best gewoon data binnenhalen en dan via php naar file schrijven? Graag ook testen in productie

ik heb dit _nu_ nodig en het werkt niet ...

**Comment by acrobat** [comment]
@tvlooy is hier nog een fix voor nodig of is d6d9f6f voldoende? Anders kijk ik er deze middag even naar!

**Comment by tvlooy** [comment]
@acrobat ik heb de exports genomen maar dit moet gefatsoeneerd worden. Niet meer dringend nu omdat ik de exports heb
