### ISSUE TITLE
Enter participants in bulk UX

### ISSUE THREAD

**Issue by guntervs** [Intracto/SecretSanta#143]
Entering a lot of participants is not user friendly. A few suggestions:
- Automatically add a new line when entering a name in the last line
- Add button "add new person" at the bottom of the list
- Provide a textarea to add participants in bulk (eg. John Doe, johndoe@example,com with each entry on a new line)

**Comment by tvlooy** [comment]
@mvanspringel 
suggestie 1: doen we niet
suggestie 2: knop onderaan ook zetten is denk ik heel goed idee
suggestie 3: dit is UX een probleem. Laat dit nakijken door Ellen

**Comment by mvanspringel** [comment]
Discussed and adopted in #251
