### ISSUE TITLE
Error 500 - Internal server error! This incident will be reported.

### ISSUE THREAD

**Issue by leocaseiro** [Intracto/SecretSanta#149]
Hi, I'd like to report that I'm getting 500 error.

I'm trying to open my email link, so I can update my wishlist, but it's not working.

PS: I've received 4 emails that seems to be a poke from my secret santa.

Thanks

**Comment by junbug178** [comment]
Experiencing the same issue. Unable to access list or participant link.

**Comment by tvlooy** [comment]
this problem is fixed. Our server was getting a bit overworked :-) Sorry for the inconvenience. I'll keep an eye on it to make sure everything stays up and running

**Comment by leocaseiro** [comment]
Thank you @tvlooy! I appreciate it!
