### ISSUE TITLE
Make wishlist "Description" field a full size window

### ISSUE THREAD

**Issue by lsmith999999** [Intracto/SecretSanta#154]
Appreciate your efforts but the field for entering your wishlist isn't an appropriate size. A single-line text box doesn't cut it (and it's also very narrow). It should be a full window for entering detailed information, which will also make it much easier to read as well. Am surprised it wasn't done this way in the first place (I'm sure many must find the existing situation annoying).

**Comment by tvlooy** [comment]
It was done like that in the first place. Then we changed it because people wanted rows.

**Comment by lsmith999999** [comment]
Hi Tom,

Thanks for the prompt reply. It was meant to be constructive since everyone will have their own opinions of course. Multiple rows is fine, since it allows each gift to be easily enumerated (and distinguished from the others), but the fields themselves are way too narrow to enter any detailed info (and also very difficult to see and review). Each should be converted to a multi-line edit control of some type, even if it simply means changing each existing text box to one with a sizing grip (so it can be expanded, though admittedly that may be unwieldy since there are multiple rows). Or perhaps add an “Edit” button that will open the text box into a full window when clicked. Note that I’m a developer myself (many years in the field), though I don’t work with UI apps as much as I once did (so I haven’t thought about the ergonomics of this in too much detail in recent years). The interface is definitely screaming for expandable fields however, since it’s difficult to work with as it currently exists (both my professional opinion and as a user). Anyway, thanks again for the feedback. Appreciated.

Regards,

Larry

**Comment by tvlooy** [comment]
UX is always hard. Your suggestion is in our issue queue now. Obviously we won't fix it this year but will definitely take a look at it for next year. Thank you for your report.

**Comment by lsmith999999** [comment]
Hi Tom,

No problem. Everything needs to be prioritized of course and you’ll probably need to do a cost-benefit. I suspect however that some users of your site (perhaps many, who knows), have likely been frustrated by it. Most users would probably never send feedback however, at least based on my experience (having been in the field for a long time). They’ll either put up with it (unless it’s paid app), or just move on. Either way they won’t recommend the site and/or (worse yet), might disparage it (not good). Two members in my own group (non-programmers) already mentioned the situation to me, though I had already noticed it myself. Anyway, it’s a free site and your efforts are certainly appreciated. It’s easy to be critical, but the site seems to work well from what I’ve seen so far, other than this one glaring issue. Kudos for your work and thanks again for the feedback. Good luck.

Regards,

Larry

**Comment by mvanspringel** [comment]
Won't fix, has been discussed with @tvlooy and won't be implemented this year.
