### ISSUE TITLE
Add an option to disable wishlists and other update emails

### ISSUE THREAD

**Issue by ShadowXVII** [Intracto/SecretSanta#162]
I've been spammed with 3 "fill out your wishlist" emails and we don't use them.
Have the ability for the user to chose whether wishlists are enabled for their Secret Santa or not.

**Comment by tvlooy** [comment]
Yes. We should do something about this. Marking this as a bug because it is annoying and putting it on the roadmap for next year.

**Comment by ShadowXVII** [comment]
It's Christmas time again and didn't see this feature added as expected :(

At our organization, we don't want to use Wishlists at all: we don't want anyone even filling them out thinking that anyone will read them, and definitely don't want reminders sent (not even one) asking to fill out a wishlist.

Wishlists should be an option at the Party level, so that it can be disabled and not used at all. The emails would not mention it, nor would participants be notified.

**Comment by tvlooy** [comment]
we decided to implement a feature to unsubscribe from these mails. We will not make an option to disable this for all participants at once and we will not disable wishlists

sorry

**Comment by ShadowXVII** [comment]
Bummer, that doesn't address the issue. We just plain don't do wishlists. It confuses participants when they get asked to fill one out.

This one seems to have a global disable, so we'll try it this year; http://www.wichtel-o-mat.de/

I'll check back at Christmas 2018 to see if it's been added :)

**Comment by tvlooy** [comment]
yeah no problem. Sometimes people ask for a specific feature that we don't have and won't do. If we have to add them all, our project gets bloated. The power of our solution is that it is simple and doesn't have too much knobs and buttons
