### ISSUE TITLE
Links in wishlist items clickable

### ISSUE THREAD

**Issue by acrobat** [Intracto/SecretSanta#168]
Request from support mails.

When a participant adds a link to their wishlist item, make sure it's clickable. We allready have a custom twig method to allow this, but just need to use it for the wishlist items

**Comment by Moskydesign** [comment]
linkify method is already applied to wishlist items but only works when the scheme is set (http/https).
We could add http as default scheme when 'www.' is detected.

**Comment by tvlooy** [comment]
I agree. We should try that
