### ISSUE TITLE
Extend Behat

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#186]
De behat testen gaan op dit moment enkel over de aanmaak van een feestje maar dit zouden we moeten uitbreiden zodat alle onderdelen (of toch zeker de essentiële onderdelen) getest zijn.

TODO:
- ~Managen van een feestje testen~
- ~Via behat ook mails nakijken (bij aanmaak feestje, uitnodigingen versturen etc). Dit kan via de ~mailcatcher api~ de swiftmailer file spool. Mails worden als files opgeslagen in `app/cache/{env}/spool`. Mailcatcher vermeden omwille van extra dependency voor travis-ci en dit zou ons niet toelaten de snelle pre-build (non sudo) containers te gebruiken.~
- Behat docs voorzien zodat het duidelijk is hoe we testen schrijven en hoe je deze lokaal kan uitvoeren

Problemen/uit zoeken:
- ~Vorige keer hadden we het probleem dat we niet meerdere contexten konden registreren als deze extenden van de `MinkContext`. Dit moet nog nagekeken worden hoe we dit wel kunnen doen~ *Fixed*
- ~Bij het testen van de manage page willen we niet opnieuw via de frontend een feestje aanmaken of afhankelijk zijn van voorgaande testen. Dus een manier vinden op via de [`background` behat stap](http://docs.behat.org/en/v2.5/guides/1.gherkin.html#backgrounds) een feestje in aanmaken waarmee in die scenarios kunnen testen~

Sources:

- [Sylius Docs](http://docs.sylius.org/en/latest/contributing/code/bdd.html) & [Sylius code](https://github.com/Sylius/Sylius/tree/master/src/Sylius/Behat). Dit is wel een zeer uitgebreide setup, maar we kunnen hier stukken/principes uithalen en bij ons op een simpele manier toepassen
- [Behat docs](http://docs.behat.org/en/latest/guides.html)
- ...

**Comment by tvlooy** [comment]
@rvanginneken hebben jullie nog vooruitgang geboekt op dit issue?

**Comment by acrobat** [comment]
Op dit moment nog geen tijd meer in gestoken, maar we willen daar wel binnekort nog wat tijd voor maken. Maar dat is misschien ook iets waar de stagair in mee kan helpen (lijkt me ook interessant te zijn?)

Ik zal de description schrijven voor wat er juist moet gebeuren

**Comment by acrobat** [comment]
Only thing left here is writing some docs on how to run the tests and how to write tests
