### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#2]
Als ze een pool aanmaken moet je betere controle doen op email adressen. Ik krijg nu te vaak de melding dat er niet gemaild kan worden naar bepaalde mensen in de pool omdat het adres niet conform is (SwiftMailer error).

**Comment by tvlooy** [comment]
Zelfde issue bij het editeren van email adressen op de management page. Kan je dat daar ook effe fixen?

**Comment by acrobat** [comment]
Fixed in #3 and #7
