### ISSUE TITLE
Feature request: change link

### ISSUE THREAD

**Issue by aethy** [Intracto/SecretSanta#20]
Someone of my list accidentally sent her secret santa e-mail to all participants, thereby exposing her secret link to everyone. It would be nice if it would be possible to send a new link and invalidate the old link. This could be realized e.g. when sending a new e-mail to the person (existing functionality)

**Comment by tvlooy** [comment]
Thanks. We probably won't fix this. We try to keep the number of options low so the tool stays easy to use.

**Comment by aethy** [comment]
NP, I could only report it...

**Comment by tvlooy** [comment]
Yes. Thank you for reporting.
