### ISSUE TITLE
Verwijderen van deelnemers

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#207]
- enkel een melding "are you sure", geen hele bevestigings box printen
- verwijderen kan altijd (niet meer naar datum van feestje kijken om te weigeren)
- toevoegen van een persoon ook toelaten (niet meer naar datum kijken om te weigeren)
- Als er excludes zijn ingegeven of als iemand self assigned wordt, dan weigeren we momenteel een remove. Dit moet vanaf nu wel toegelaten worden met een simpele melding "are you sure" met de info dat de hele pool opnieuw getrokken wordt en iedereen iemand nieuw zal toegewezen krijgen en "if this is not what you want *do not confirm this message*".

**Comment by mvanspringel** [comment]
Removal of participants is now simpler and always possible. Removal of participants when using excludes can be discussed in #151 .
