### ISSUE TITLE
Mailinglist uitnodigen

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#21]
Feature request. De mogelijkheid om 1 of meerdere adressen uit te nodigen, waarbij dit ook mailingslists kunnen zijn. Iedereen die de uitnodiging ontvangt kan voor een bepaalde deadline zichzelf inschrijven op de secret santa pool. Als de inschrijvingen zijn afgerond worden de combinaties pas verstuurd. Dit zou vb: bij intracto handig zijn om niet met een google form te moeten rondvragen wie er wel of niet mee doet en dan emailadressen over te moeten typen.

**Comment by mvanspringel** [comment]
Won't fix, has been discussed with @tvlooy and won't be implemented this year.
