### ISSUE TITLE
Test emails for spam and potential issues

### ISSUE THREAD

**Issue by mvanspringel** [Intracto/SecretSanta#218]
Test emails with [mail-tester](https://www.mail-tester.com/) and fix potential issues. 

- [x] Add alt-tags to the images in emails
- [ ] Check text-to-image ratio: Add text or remove images
- [ ] Check if posible to implement rDNS & DMARC record
- [x] Add link to unsubscribe (See other issues regarding unsubscribing)

**Comment by mvanspringel** [comment]
Alt tags have been added to the base email template, and mails have been checked again. Emails now passed this section. 

Emails received a score of 9.5/10. Main todo now is to improve text-to-image ratio.

**Comment by tvlooy** [comment]
unsubscribe moet worden:

"je doet nog steeds mee met het feestje, maar je zal geen update e-mails meer ontvangen"

**Comment by tvlooy** [comment]
voorlopig ok zo
