### ISSUE TITLE
Hover State for Draggable Items

### ISSUE THREAD

**Issue by R-V-S** [Intracto/SecretSanta#22]
Tiniest of nitpicks: I think the cursor should change to a 'move' or 'pointer' cursor when hovering over a wishlist item, since it's draggable. At present, it doesn't do this (at least not in the latest stable Chrome).

**Comment by tvlooy** [comment]
@TomCan would you like to take a look at this?

**Comment by joericlaes** [comment]
Fixed in:
https://github.com/Intracto/SecretSanta/pull/44
