### ISSUE TITLE
Bug: null passed to FormRenderer:renderBlock()

### ISSUE THREAD

**Issue by mvanspringel** [Intracto/SecretSanta#234]
"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Symfony\\Component\\Form\\FormRenderer::renderBlock() must be an instance of Symfony\\Component\\Form\\FormView, null given

Matched route: Entry_view
Controller: Entry\ShowController::showAction

**Comment by tvlooy** [comment]
I'm pretty sure this was it. We'll reopen if it wasn't.
