### ISSUE TITLE
Ability to send (secret) reminders

### ISSUE THREAD

**Issue by maxvdh** [Intracto/SecretSanta#25]
A great feature of for instance lootjetrekken.nl is that paired users can send anonymous messages to the person they have been assigned to, to for instance:
- ask this user to update their wishlist
- ask for specific clarifications on the wishlist

Specifically the first use case could be valuable as this something that tends to be forgotten often.

Best,
Max

**Comment by tvlooy** [comment]
That would be a great improvement. I want to add to this list that an often requested feature by pool admin is to send mail to all members.

**Comment by tvlooy** [comment]
This mail can be used to add amazon product tips.

**Comment by acrobat** [comment]
This was also requested through email support. I've added the 2017 season milestone to have this implemented next year

**Comment by tvlooy** [comment]
implemented by @mvanspringel
