### ISSUE TITLE
[RFC] Translation bundles

### ISSUE THREAD

**Issue by mvanspringel** [Intracto/SecretSanta#273]
The current translation files are quite extensive, not really structured, and difficult to work with. We should try and find some method to make working with them more easy. Maybe we should use some sort of bundle or maybe save them in the DB,...

An option might be [LexikTranslationBundle](https://github.com/lexik/LexikTranslationBundle), possibility to manage translations, import/export them, including GUI to edit and check if everything is translated,... 

Please discuss possible solutions.

**Comment by tvlooy** [comment]
won't fix (developer shortage)
