### ISSUE TITLE
Prevent specific pairings

### ISSUE THREAD

**Issue by tincansandtwine** [Intracto/SecretSanta#28]
Need the ability to control who a person should not be paired with, eg., spouses (who are generally given gifts outside of secret santa) and the person who you got last year.

**Comment by hvanoch** [comment]
I created a branch with a working example for thuis feature. Stille needs a bit of worm before merging.

**Comment by tvlooy** [comment]
Wow, cool. Looking forward to the PR!

**Comment by hvanoch** [comment]
The branch is in this repository.

**Comment by tvlooy** [comment]
Ping me when it's ready for review and merge Henne.

**Comment by hvanoch** [comment]
Forgot to ping you, it was ready 2 months ago. 
Could you have a look at the branch exclude-entries?

**Comment by tvlooy** [comment]
Works. Error message is not so user friendly but hey. Merged. We should give this project another hackathon to cleanup and rewrite some stuff.

**Comment by tvlooy** [comment]
thanks @hvanoch ^5
