### ISSUE TITLE
Problem updating wishlist

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#30]
Some people update their wishlist, click update and the wishlist is gone. I can't reproduce but it is frequently reported so must be looked at. Complete rewrite if nesessary.

While there, cleanup support for old wishlists. Might fix the bug above. Who knows. Less code means less bugs anyway.

**Comment by mvanspringel** [comment]
Old wishlists are removed. This issues is not reproducible. Close for now
