### ISSUE TITLE
Multilanguage with detection

### ISSUE THREAD

**Issue by StryKaizer** [Intracto/SecretSanta#31]
If we want to conquer the world, we need to provide their language.

Autodetection based upon browser and as many languages as possible (lets start with dutch, shall we ;) )

**Comment by IntractoSupport** [comment]
This was implemented partially by @hvanoch 
Todo: add language switcher flags. Ask Tom Van Mierlo's opinion on how this should look.
Poke people doing portugees (Pieter M) / spaans (Tom VM) / chinees (Karman) to finalize translations.
Find people to translate to russian and other languages ...

**Comment by tvlooy** [comment]
some translations are still todo but will poke more people for this in the coming weeks
