### ISSUE TITLE
Extend behat test suite

### ISSUE THREAD

**Issue by acrobat** [Intracto/SecretSanta#322]
List of things we should add to the behat suite

- [x] create party with csv upload. See #324 
- [ ] commands
- [ ] participant excludes with select2
- [ ] Email content (btn click, etc)
- [ ] Fix false-positive on load from csv test. See https://travis-ci.org/Intracto/SecretSanta/builds/269103204
- [ ] ...

**Comment by tvlooy** [comment]
@acrobat kan je even updaten wat in orde is?

**Comment by acrobat** [comment]
Alle todo's van hierboven zijn nog steeds todo. Die false-positive fix is op zich wel al gedaan (extra scrollTo naar de knop gedaan) dus even bekijken als travis hier nog random op zou failen, maar denk dat dit nu wel goed. Dus die todo kunt ge wel al afvinken volgens mij

**Comment by tvlooy** [comment]
won't fix (developer shortage)
