### ISSUE TITLE
[RFC] Switch license from ISC to GNU AGPLv3

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#323]
We currently license this project under ISC, which means anyone can take this project and modify / distribute it, make it closed source or sell this code / relicense it. As long as they do not delete the current license and copyright notes from the code that is all fine. We are only protected against responsibility claims and we also don't provide a warranty.

I would like protect to the project against competitor forks by switching to the GNU Affero General Public License v3.0 (AGPLv3). This would mean that the code must stay AGPLv3 and has to be released if it is used to offer a service over the network. A competitor will still be able to use our work but would have to publish all changes to the code so we can get changes back.

Does this mean we ourselves also can't make closed source extensions to the project in the future? Yes and no. Extending it with closed source parts would mean that we have to do it in a separate codebase that reads the same DB or provide an API and consume that. I'm fine with that.

Because we are growing, this seems a healthy thing to do now.

We are not voting yet. This will be discussed with @acrobat first.

This is a list of contributors. Can everyone OK / NOK this with a reply to this issue please?

- [x] Tom Van Looy
- [ ] Niels Roels
- [ ] Jimmy Henderickx
- [ ] Mats Vanspringel
- [ ] Jeroen Thora
- [ ] Henne Van Och
- [ ] Alexandre Tozzi
- [ ] Joeri Timmermans
- [ ] Tom Cannaerts
- [ ] Jeroen Tubex
- [ ] Joeri Claes
- [ ] Roy Van Ginneken
- [ ] Joris Vercammen
- [ ] Jeroen Moons
- [ ] JanDC
- [ ] Sead Memic
- [ ] Karman Li
- [ ] Wouter Van Scharen
- [x] Service and Maintenance
- [ ] Vincent Verhasselt

**Comment by tvlooy** [comment]
too much downsides vs too little upsides

**Comment by acrobat** [comment]
Ok we will keep it then!

**Comment by tvlooy** [comment]
It's something to think about. But, I had the feeling that we were going to shoot ourself in the foot by changing the license. Better leave it as is for now and do some more thinking first
