### ISSUE TITLE
Participant email status is wrong

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#343]
Kayako ticket 310960

mail status says "not received" but participant confirms it was received and opened

**Comment by mvanspringel** [comment]
Tested but unable to reproduce. Tested with multiple parties, multiple emails (providers) and multiple mail clients. All showed the correct status of the mail. No false positives

**Comment by tvlooy** [comment]
Thanks for taking the time to check this @mvanspringel
