### ISSUE TITLE
reordering wishlist items needs adapted cursor

### ISSUE THREAD

**Issue by geertvansteyvoort** [Intracto/SecretSanta#35]
I think it's commonly accepted to use 
![image](https://cloud.githubusercontent.com/assets/16050592/11446799/8f151dbc-953c-11e5-98db-ee520ae16148.png) when dragging stuff, no?

**Comment by acrobat** [comment]
Fixed in #44

**Comment by tvlooy** [comment]
't is een veusje geworden Geert ;-)

**Comment by joericlaes** [comment]
"cursor: move" in css geeft in sommige browsers een veusje & soms 4 pijlen :)

Built-in cursors may look different depending on what browser/operating system is being used. For example, some browsers (e.g. Firefox on Windows 7) will show the move cursor as a four-pointed arrow ([Four-Pointed Arrow Cursor]) while others (e.g. Firefox on Mac OS X) will show a hand ([Hand Cursor]). Using custom cursors, you can ensure all applications are using the same cursor for a more consistent expeience. The example below is the same as the one above, except in all browsers, you will see the a hand icon.

**Comment by tvlooy** [comment]
dus conclusie goeie software geeft veusjes. Linux, Firefox, ... En andere software een kruis, ... ;-)
