### ISSUE TITLE
Suggestion: team for secret buddy

### ISSUE THREAD

**Issue by glittle** [Intracto/SecretSanta#354]
My group would like to have two people collaborate to purchase gift(s) for each person.

For example, if you have people: A, B, C, D, E, F

A's name would be given to two people, say: C & F.  C and F would each be able to view the gift list for A, and are told of each other - they are given each other's name and email address so that they can talk together and decide what gifts they will give to A. This gives them the option to pool their gift budget to get a larger gift for A.

**Comment by tvlooy** [comment]
thanks for the suggestion. It is very unlikely that we will do this but I will keep this open for RFC to give it some thought

**Comment by tvlooy** [comment]
We decided to not schedule this for our next version. Maybe some day we will have room for this kind of features but the goal is to keep the tool as simple as possible for the users and for de development maintenance.

**Comment by glittle** [comment]
Thanks for considering it!
