### ISSUE TITLE
Change the way people are matched after the party has started

### ISSUE THREAD

**Issue by TomCan** [Intracto/SecretSanta#363]
If a user is added to the party after it has been started, the manager is matched with the new participant, and the new participant is matched with the original match of the manager, which spoils the secrecy to some extend. We should change this to first check if there are any participants who haven't yet checked their match. If so, we could use that participant to match against instead of the manager.

**Comment by tvlooy** [comment]
I like the idea.

**Comment by tvlooy** [comment]
won't fix (developer shortage)
