### ISSUE TITLE
bg image overlap bij enkele talen op mobile

### ISSUE THREAD

**Issue by RubenHollevoet** [Intracto/SecretSanta#364]
Bij enkele talen (bv Nederlands) is er een overlap tussen tekst en background image op mobile.
![capture](https://user-images.githubusercontent.com/34029274/33268175-88b52824-d37c-11e7-9591-66bdea6368e5.PNG)

**Comment by tvlooy** [comment]
@joericlaes wat denk je van deze oplossing?
![screenshot from 2017-11-28 13-44-14](https://user-images.githubusercontent.com/391674/33320383-5a031a6a-d442-11e7-8169-b303d75c98fe.png)

**Comment by joericlaes** [comment]
Deze oplossing gebruiken wij ook vaak in andere projecten. Goed voor mij, gewoon zien dat de alpha waarde hoog genoeg staat zodat je de tekst duidelijk kan lezen.

**Comment by tvlooy** [comment]
@joericlaes kan je deze even reviewen?
