### ISSUE TITLE
Missing MySQL Database Structure

### ISSUE THREAD

**Issue by tiagosampaio** [Intracto/SecretSanta#365]
Hey guys, how are you doing?

I'm trying to set up this application in my localhost but I'm getting an error with the database. I don't have the database structure to setup it up in my local environment. I'm using a docker with a configuration of mine.

Could you assist me with this?

Thanks!

**Comment by stevenMondelaers** [comment]
Hi, you should be able to generate the database by running `php app/console doctrine:schema:create` in the project root.
This is something our shell provisioner does for us when configuring our vagrant environment, I encourage you to take a look at our shel provisioner to better understand how we set up our dev environment.

Please let me know if you have any questions.

**Comment by tiagosampaio** [comment]
Thank you so much!
