### ISSUE TITLE
Generating wrong HTML content when pressing ✏️ icon multiple times

### ISSUE THREAD

**Issue by RubenHollevoet** [Intracto/SecretSanta#366]
Occurs on PC and mobile when pressing the ✏️ icon a second (or more) time

![screenshot_20171127-204258](https://user-images.githubusercontent.com/34029274/33285974-45d8cf96-d3b4-11e7-96b8-1bf4ce66a899.png)

**Comment by tvlooy** [comment]
nice catch @RubenHollevoet
