### ISSUE TITLE
Possible to see all participant's secret santa

### ISSUE THREAD

**Issue by hvanoch** [Intracto/SecretSanta#372]
As an admin you can see all participant's secret santa without them knowing by coping the hash from the URL on the 'manage' page and use it in the 'participant' page.

**Comment by tvlooy** [comment]
There is a link on the management page to show the combinations. If the admin clicks that button, we don't tell the participants that the admin knows the combinations anymore.

So, why bother using the hashes of the participants? :-)

**Comment by hvanoch** [comment]
I didn't know that the telling the participants that the admin knows the combination was removed :-)

**Comment by tvlooy** [comment]
:-)

There were many people that asked questions about that part. Like "will they see the combinations too"? And the "eye" icon that was displayed caused confusion as well. I was not worth it.

We removed sending the combinations by email to 1) send less email and 2) don't get questions about the email not arriving for some reason.
