### ISSUE TITLE
Add "how does it work"

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#40]
some people don't understand the full process, eg: it's not clear that we support a wishlist etc. There should be something that explains the entire process from create pool to delete pool so people know what to expect.

Reported by nickvh

**Comment by IntractoSupport** [comment]
Make a "how does it work" page that looks cool and shows that:
- we are fee
- we honour your privacy (we don't use your individual data)
- how our secretsanta works
- you can delete your list
- you can expose the combinations tot the list admin
- we have wishlists
- it's possible to change email addresses and resend mails
...

Part 1 should be that this is on a permanent webpage.
Part 2 should be for an update e-mail to notify our past users.

**Comment by tvlooy** [comment]
FAQ is done (en / nl). Proofreading is requested and French translations are requested too.
