### ISSUE TITLE
Get list with matches

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#41]
admin should be able to get the entire list with matches. This is a often requested feature. You can now only peek at individual level (only in development).

Add an option to mail the combinations to the admin and add a visible indicator that the list was sent and "exposed" to the admin.

**Comment by tvlooy** [comment]
we could automatically expose the pairs on the admin page on the day of the party ...

**Comment by rvanginneken** [comment]
On manage page:
Both with delete & expose -> add "Cancel" button to revert buttons
(move js out of HTML)

**Comment by tvlooy** [comment]
@rvanginneken beetje meer gebruiksvriendelijke mail mag wel. Dit is te basic

**Comment by tvlooy** [comment]
ping @rvanginneken

**Comment by rvanginneken** [comment]
I'm waiting for my French translations. I'll put it in and fix the mail together.

**Comment by rvanginneken** [comment]
I changed my translation a bit to make it more consistent with the existing translations. Had to request new translations.
Will create PR when I've put those in.
