### ISSUE TITLE
Batch e-mails causes memory issues

### ISSUE THREAD

**Issue by TomCan** [Intracto/SecretSanta#41]
When a large number of reminders e-mails need to be send, the process gradually consumes more and more memory as it advances through the batch. This can lead to very slow processing and eventually out of memory issues.

Instead of trying to send them out all at once, this should be done in smaller batches. This also allows the e-mails to be spread trhoughout the day, rather than once every night.

**Comment by TomCan** [comment]
This is also related with #28. 

I think the best solution would be to make an e-mail queue that receives all e-mails to be sent (registrations, new lists, reminders, ...) and then have a worker process a given number of e-mails at a time. We could add some sort of prioritizing in there so that important e-mail are sent immediately and less important afterwards.

By using a queue and worker setup, we could recycle the workers more often, preventing memory leaks. As all e-mails are sent from the same place, it would probably make debugging/logging easier as well.

**Comment by tvlooy** [comment]
Indeed. I was also thinking in that direction.

**Comment by tvlooy** [comment]
This is possibly fixed by rewriting parts of the application. First stresstest locally to see if the application breaks. If that is the case, we can look at possible solutions.

**Comment by Miljar** [comment]
Which branch is it? Maybe I can help with the stresstests

**Comment by tvlooy** [comment]
everything is in master. There is no work open. This is a ticket from before the thing was reworked. So test and try to break things in master :-)

**Comment by pix-art** [comment]
We could also just spool by file: http://symfony.com/doc/current/cookbook/email/spool.html#spool-using-files

This will write the email to a folder and you setup a cron with a limit of 50 or 100 like tom said:

```
php bin/console swiftmailer:spool:send --message-limit=10 --env=prod
```

**Comment by tvlooy** [comment]
No issues last seison
