### ISSUE TITLE
Translation for confirmation message with reuse-function

### ISSUE THREAD

**Issue by dailybits** [Intracto/SecretSanta#412]
When filling in https://www.secretsantaorganizer.com/reuse your'll receive the Dutch confirmation message:

"We hebben je mail verzonden!"

It's missing EN translation.

**Comment by tvlooy** [comment]
I cannot reproduce this. For me it's the reverse. I am on the NL site and get the EN message.

The message is translated in both languages see https://github.com/Intracto/SecretSanta/blob/master/app/Resources/translations/messages.en.yml#L699 and https://github.com/Intracto/SecretSanta/blob/master/app/Resources/translations/messages.nl.yml#L713

what makes it weird is that the "error" message that is below the success message behaves correctly ...

**Comment by tvlooy** [comment]
cannot reproduce
