### ISSUE TITLE
Things I'd like to see

### ISSUE THREAD

**Issue by tamikeehn** [Intracto/SecretSanta#413]
We don't like the wish list option, so used our own favorite things list, but we are still getting reminded that we didn't create a wish list.  We are a small office and don't want to spend a lot on our gifts, so Amazon is not really a good option.  Also, since this is our first year, we had an issue with people getting the same people they had last year, as I didn't know to do exclusions, so I just had a couple of them trade, but there is no way to reflect that in my list.  I'm not a coder, so maybe someone else could work on this?  Other that these items, I think it works very well, and I like the reminders and the ease of setting things up.  Thanks,

**Comment by tvlooy** [comment]
thank you for your feedback. Unfortunately at the moment we can't take any feature requests because of lack of people that can do the work
