### ISSUE TITLE
Store ongoing parties locally

### ISSUE THREAD

**Issue by RubenHollevoet** [Intracto/SecretSanta#418]
The idea is to save tokens of parties you manage or are invited to in the cookies/local storage so you can directly navigate to your ongoing parties from the homepage and avoid the hassle of searching through your mailbox.

![image 3](https://user-images.githubusercontent.com/34029274/48759750-68b0a980-eca4-11e8-8739-b9d7132a64be.png)

**Comment by tvlooy** [comment]
I love the idea. If you can find the time to code it up let me know!
