### ISSUE TITLE
Responsive (SEO) text blocks

### ISSUE THREAD

**Issue by joericlaes** [Intracto/SecretSanta#42]
Recently, there were some blocks of text added. The styling of these blocks on mobile devices isn't ideal.

See the screenshot below for example:
https://www.dropbox.com/s/yn2wi3gxbccvzfm/Screenshot%202015-12-04%2019.54.52.jpg?dl=0

**Comment by tvlooy** [comment]
ge kunt in github zelf een image uploaden trouwens, gewoon in een comment veldje slepen ...

**Comment by joericlaes** [comment]
Oké :) thx.
