### ISSUE TITLE
Mails are not delivered to yahoo.com

### ISSUE THREAD

**Issue by webmake** [Intracto/SecretSanta#462]
Hello,

recently we created list, but one receiver could not get an email "Email not delivered!"

The only resource that I found is https://www.downreporter.com/blog/yahoo-mail-not-receiving-emails-unable-receive-mail/

You can see in action https://mxtoolbox.com/SuperTool.aspx
smtp:yahoo.com ->  | SMTP Connect | Failed To Connect

smtp:smtp.mail.yahoo.com
220 smtp.mail.yahoo.com ESMTP ready

**Comment by tvlooy** [comment]
this is Yahoo not delivering email. It's like the postman ate your letter. As we don't control external mail servers, the only suggestion I can make is to use another provider

**Comment by tvlooy** [comment]
Yahoo will now be delivered by Mandrill. This joke will cost us extra money :(

**Comment by webmake** [comment]
Thank you a lot, I confirm, this was solved
