### ISSUE TITLE
I want to add constraints for the attribution of presents

### ISSUE THREAD

**Issue by Laurebl** [Intracto/SecretSanta#466]
Hi Secret Santa team,
I tried to use it for a Christmas Party with my large family but the problem is that I would like to add constraints in the attribution of presents. For instance, I would like to make it impossible that my brother pick up his wife.

Do you think it's possible to add this feature ? 

Thank you,
Laure

**Comment by tvlooy** [comment]
No sorry we won't provide this feature.
