### ISSUE TITLE
Improvement to "add new participant" when party already has been started

### ISSUE THREAD

**Issue by TomCan** [Intracto/SecretSanta#468]
When a participant is added to the party when the party has already been started, the new participant will be added at the position of the manager of the party (manager gets the newly added participant assigned, which in turn gets the previous match of the manager assigned). 

This is also the case when there are still participants that have not yet viewed their match. In such a case, it would make sense that one of the persons who haven't yet retrieved their match is used instead of the manager of the party. Since they haven't viewed their match yet, they aren't aware that it changed anyway.

**Comment by tvlooy** [comment]
Can you send a PR that implements this or find someone that can?

**Comment by sweetpatato** [comment]
What else I noticed is that when a participant is added to the party when the party has already been started, the new participant haven't been choosen from anyone :( And one of the pleople have been choosen twice.

**Comment by tvlooy** [comment]
@sweetpatato can you email your party details to tom.vanlooy@intracto.com?

**Comment by tvlooy** [comment]
fixed by @TomCan
