### ISSUE TITLE
error after 20 participants

### ISSUE THREAD

**Issue by damsk8** [Intracto/SecretSanta#473]
I can't add more than 20 people in the organizer.

I have a red warning on the 21.

**Comment by tvlooy** [comment]
it is possible that the 21th person you try to add has blacklisted him/herself and does not want to participate in secret santa parties

our tool should be able to handle an "unlimited" number of participants

**Comment by damsk8** [comment]
i try with another mail adress and same problem at the 21

**Comment by RubenHollevoet** [comment]
I have just created a party with 23 participants and I am unable to reproduce. All participants have received their email.

**Comment by damsk8** [comment]
Oh, it was the mail on one participant i put another one and it works... Is there a limit size for the mail adress?

**Comment by tvlooy** [comment]
no any address that is accepted by the internet standards will be accepted by us
