### ISSUE TITLE
Markup is broken in Russian version

### ISSUE THREAD

**Issue by anastas-makar** [Intracto/SecretSanta#476]
![screenshot-www secretsantaorganizer com-2019 12](https://user-images.githubusercontent.com/57357389/69970563-822f3700-152f-11ea-9b91-d18745de3fe7.png)

**Comment by anastas-makar** [comment]
May be it is not a bug, but in English version the letters do not overflow the Santas dress, so they are more readable.

**Comment by tvlooy** [comment]
yeah that's not good ... Thanks for your report. We'll look into this and try to find a fix

**Comment by gijsroge** [comment]
@tvlooy fixed, I did have issues with CRLF line endings and PhpStorm ended up modifying all line endings.. 🤦‍♂️

**Comment by tvlooy** [comment]
thanks @gijsroge ! This is in production
