### ISSUE TITLE
Santa is cut in two halves in Russian version of letter

### ISSUE THREAD

**Issue by anastas-makar** [Intracto/SecretSanta#477]
![screenshot-e mail ru-2019 12](https://user-images.githubusercontent.com/57357389/69971990-d5a28480-1531-11ea-9e87-7120e2720086.png)

**Comment by tvlooy** [comment]
valid point. We'll have a look at this

**Comment by tvlooy** [comment]
@anastas-makar is this on a specific email client?

**Comment by anastas-makar** [comment]
That was web-version (opened in Chrome, then in Firefox). In Thunderbird quite the same.

**Comment by anastas-makar** [comment]
*email service: mail.ru
*OS: Ubuntu Linux

**Comment by tvlooy** [comment]
Fixed
