### ISSUE TITLE
questionnaire

### ISSUE THREAD

**Issue by S2Saathoff** [Intracto/SecretSanta#482]
Hi - rather than make a 'wish list' for each participant - I'd like to have people complete a questionnaire (with questions that I provide - or choose 10 questions from a list of 30 - or ??? ) - so we can all learn about each other (rather than just be materialistic - this is what I want you to buy).  Anyone participating would be able to see the answers; but who you are paired with would still be random/secret.    Any chance this is possible?

**Comment by tvlooy** [comment]
No sorry. We cannot add your request to our shortlist. It is already possible to (optionally) share a page with all wishlists with the participants.
