### ISSUE TITLE
Feature proposal: Exclusion list

### ISSUE THREAD

**Issue by GerkinDev** [Intracto/SecretSanta#485]
Hi people ! Your app is nice, but my friends requested a feature that does not exist: the match exclusion list. It has already been requested in #375, so I'm proposing it back.

I can do a PR if you want (tests included)

### Front:

A new field would be added to the participants table. This input would be a select with multiple options, each option being one of the participants' name.

### Models

A new field would be added in [Entity/Party](https://github.com/Intracto/SecretSanta/blob/master/src/Intracto/SecretSantaBundle/Entity/Party.php), that could be either:
* a list of a new Entity *ParticipantMatchExclusion* containing the fields: `{from: Participant, to: Participant}`
* or a JSON serilalization of an object with the same structure as above, since there is no need to query this field. In case of update of participants list, invalid IDs would be simply discarded.

**Comment by RubenHollevoet** [comment]
Hi @GerkinDev 

good news! This feature is already part of the project.
To make an exclusion list, you first need to create the party.
After that you end up in the admin panel where you can make the exclusions before sending out the emails to the participants.

![image](https://user-images.githubusercontent.com/34029274/70693530-ec797180-1cbd-11ea-9769-ea0a80cfda57.png)

This field appears when pressing the "Exclude certain combinations" button.

I also believe the party need to have a minimum of 4 people.

**Comment by GerkinDev** [comment]
Oh, my bad, I did not saw it... Thanks!

**Comment by RubenHollevoet** [comment]
hi @GerkinDev,

This feature is already live for at least one year.
Can you send the party admin link to ruben.hollevoet@intracto.com and I will have a look.
