### ISSUE TITLE
Refactor proposal: move from javascript to Typescript

### ISSUE THREAD

**Issue by GerkinDev** [Intracto/SecretSanta#486]
In order to facilitate readability of front-end code, I suggest moving from javascript to Typescript. It would greatly help people understand the code even if they are new.

I can do the setup & rewrite for you if you want.  It would also help me for the feature proposed in #485.

**Comment by JanDC** [comment]
Hi @GerkinDev ,

An excellent proposal! We'd love to review (and assist your with) your rewrite.
