### ISSUE TITLE
Option for host not to participate

### ISSUE THREAD

**Issue by hey-euge** [Intracto/SecretSanta#499]
Firstly, thank you for sharing this open-source application.

I'm about to create a party for all the kids in my family including nieces and nephews. As the adult organizer, it would be nice to have the option to set up the party without participating.

I did a quick test and it looks like this workaround will work:
- Use my email address as the host.
- After I receive the initial email with the Management link, I change my email to one of the kid's emails.
- Start the party.

**Comment by tvlooy** [comment]
I understand that this is something some people want and you are not the first one to ask. The workaround you applied is actually perfect. We try to keep the number of knobs we add as low as possible to limit the number of decisions people have to make. Maybe we will add this as an option in the future, but I don't see room for this in the near future
