### ISSUE TITLE
Host Exclusion

### ISSUE THREAD

**Issue by FGirl186** [Intracto/SecretSanta#503]
First, I love your website!!  I spent a fair bit of time trying to find a website that works for me this year, and this is by far the best.  I love the feature of being able to manage the party after it's been set up.  The only feature I would ask to be included is that the host isn't automatically included in the party.  I am a youth leader at my church, and I am helping to facilitate a virtual gift exchange this year.  I do not want any of the kids to get me as someone they need to get a gift for, and I was not planning on gifting any of the kids.  It would be great if there was a checkbox next to the host to choose to opt-in, or opt-out.

**Comment by tvlooy** [comment]
I understand that this is something some people want and you are not the first one to ask. A workaround that can be applied is:

- Use your email address as the host.
- After you receive the initial email with the management link, change your email to one of the kid's emails.
- Start the party.

We try to keep the number of knobs we add as low as possible to limit the number of decisions people have to make. Maybe we will add this as an option in the future, but I don't see room for this in the near future
