### ISSUE TITLE
A person has an "Email Not Delivered" status but receives the email after several "resend emails"

### ISSUE THREAD

**Issue by dhrumilp15** [Intracto/SecretSanta#511]
I started a party and saw that some email addresses had an "Email not delivered" status. I contacted these people and they received the party invite email a few minutes later. I did press "resend email" three times in total for one person and they received one email in their inbox and 2 in spam. After a refresh and they opened the email, the status changed to an "opened email". 

To reproduce:
- Start a party and there might be emails that have an "Email Not Delivered" status

**Comment by tvlooy** [comment]
there can be a delay on the mails, some providers don't like the fact that we send out a lot of emails (we just have a lot of users) and will flag us as spam. There is a tracking pixel in the mail so we can inform the party admin that an mails was opened, but offcourse this is best effort.
Can you send me info about your party? I will have a closer look. Use https://www.secretsantaorganizer.com/contact and mention Tom Van Looy in your email.
