### ISSUE TITLE
Master List of Allocation must be visible only to Admin

### ISSUE THREAD

**Issue by manojkp04** [Intracto/SecretSanta#52]
Hi,

Currently if the admin wants to know the allocations, he has to enter " Show Me Everything". The same list is send to all members who have registered. Hence there will be no privacy. The entire team will get to know the list and allocation.

Kindly make a provision where only the Admin can see the allocation list. The admin can monitor the event and make sure that gifts are exchanged without compromising the privacy of the players.

Kindly do it asap..

Regards
Manoj

**Comment by tvlooy** [comment]
"Show me everything" will send the combinations to the admin only. The participants will only get notified of the fact that you know the combinations.

So it works the way you want.

We will clarify the info text because you are not the only one that is confused by this.

**Comment by manojkp04** [comment]
Hi,

That's great. Thank you for the reply and the immediate fix.

Regards
Manoj
