### ISSUE TITLE
How is the mysql database schema generated?

### ISSUE THREAD

**Issue by jmilette** [Intracto/SecretSanta#531]
I'm attempting to stuff this all into a docker container, and I have 98% of it done, but I can't figure out what populates the mysql database.  The only sql file I'm seeing is this:  https://github.com/Intracto/SecretSanta/blob/1f05a66c6f0d5e6b3dfd370dbd0d8e9d436b9bc4/shell_provisioner/config/postfix_bounce.sql

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'secretsanta.blacklist_email' doesn't exist` is my current error, any advice as to where that table is created would be awesome.

**Comment by jmilette** [comment]
Looks like `bin/console doctrine:schema:update --force` is what I need!

**Comment by tvlooy** [comment]
Correct! @jmilette

**Comment by tvlooy** [comment]
You know we would love to accept your changes so feel free to open pull requests.

**Comment by jmilette** [comment]
I've never actually submitted a pull request, still learning git.  I'll give it a try though if you want a Docker setup that will build an image from this repo.  Not sure how best practices it is, but it works nicely.

**Comment by tvlooy** [comment]
Give it a try. Done is better than perfect ;-) and we'll help you where we can or polish up things where needed.

**Comment by xgaia** [comment]
@jmilette can you publish your dockerfile ? I am very interested in deploying the app with docker

**Comment by jmilette** [comment]
Hi @xgaia:  You can check it out here:  https://github.com/jmilette/-secret-santa-builder

Its a mirror of my internal git repo, so various links aren't correct, as well as it uses my personal apache2 server as a base, you can find the source for that here:  https://github.com/jmilette/apache2-phpfpm

Moving it to a generic http container and streamlining it a bit is on my todo list, after which I'll submit a pull request - in the mean time feel free to use as-is :)

**Comment by xgaia** [comment]
Thanks @jmilette I will try to deploy my own instance
