### ISSUE TITLE
Hardcoded link on home page

### ISSUE THREAD

**Issue by jmilette** [Intracto/SecretSanta#532]
Hi!  The link below appears to be hard-coded to https://www.secretsantaorganizer.com, instead of using the current site URL as defined by `HOST` in .env

![image](https://user-images.githubusercontent.com/83293875/135624614-6004edf6-2144-4416-952e-eefa94ec052d.png)

The rest of the links (privacy policy, etc) appear to be linked correctly.

**Comment by tvlooy** [comment]
Yeah ... the domain name is in translation yaml files. While it's maybe not ideal, I didn't expect this to be an issue. What issue do you have with it? I opened a PR with a suggestion to fix it in #533

**Comment by jmilette** [comment]
> Yeah ... the domain name is in translation yaml files. While it's maybe not ideal, I didn't expect this to be an issue. What issue do you have with it? I opened a PR with a suggestion to fix it in #533

Is only really an issue for self-hosting the project.  Thanks for the rapid fix!
