### ISSUE TITLE
Adding images withing the wishlist

### ISSUE THREAD

**Issue by KeiCas** [Intracto/SecretSanta#538]
It should have the option to add images with every item in your wish list, that way your secret Santa will get a better idea of what you want, sometimes is hard to explain with just words, because we want something very specific.

Images are better than words ;)

**Comment by tvlooy** [comment]
you can link to image URL's that you can find in google search etc.
but hosting the actual images makes us a lot more vulnerable to abuse. I don't think we are going to do this without having someone that really wants to invest his/her time into the feature

also note that this is an issue tracker on a code collaboration platform, so feel free to come up with an implementation

**Comment by KeiCas** [comment]
How do I link?
I didn't see that option, if so I agree with you, no need more.

**Comment by tvlooy** [comment]
Say I want this sweater: https://litb-cgis.rightinthebox.com/images/640x640/202110/bps/product/inc/fdbnxw1635500067851.jpg?fmt=webp&v=1 you can just put that link in your wishlist item. Can you try that?

**Comment by KeiCas** [comment]
Yes, thank you, the site is down now (or at least my friend and I cannot enter), but I got what you said.

**Comment by tvlooy** [comment]
I see. Fixed thanks!

**Comment by KeiCas** [comment]
Thanks a lot, already put the link.
