### ISSUE TITLE
Website timing out

### ISSUE THREAD

**Issue by lewymd** [Intracto/SecretSanta#539]
Hi,

Sorry this probably isn't the best place for it but your contact page won't send either., in case you aren't aware there seem to be some issues with the site my whole party are getting constant time out errors, if you are lucky the page might load after a dozen attempts.

I love the site and thanks for your work!

Lewis

**Comment by tvlooy** [comment]
seems like we are having a massive ammount of users this year. I'm keeping an eye on it now. Thanks for sharing this info
