### ISSUE TITLE
Improve website performance by checking google pagespeed insights

### ISSUE THREAD

**Issue by JanDC** [Intracto/SecretSanta#55]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.secretsantaorganizer.com%2F&tab=desktop

Some easy gains:
 - minify html: add spaceless tag around the body of pages to reduce page size (and remove comments)
 - Removed render blocking assets: use async and try to split up css delivery by it's priority (above/below fold)
 - Cache assets: if assets are cachable, provide them with an expire date
 - Minify JavaScript/CSS: By using assetic(already bundled) or a frontend alternative

Somewhat harder:
 - lossly compress image to reduce bandwidth (Haven't got experience)

**Comment by tvlooy** [comment]
:+1: zal sowieso niet meer dit jaar live gaan. Enkel nog echte bugfix deploys dit seizoen (> 2 weken)

**Comment by JanDC** [comment]
Ik ging toch eerst eens zien naar de bugs, maar performance is ook belangrijk he ;)

**Comment by tvlooy** [comment]
ah maar hou u vooral niet in hoor, maar ik merge het pas binnen 2 weken ;-)

**Comment by NielsRoels** [comment]
Has been improved with #104 

Might still need some sort of critical CSS tool to improve speed even more, this might be opened in new issue.
