### ISSUE TITLE
Reply to wishlist reminder

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#57]
People reply to the wishlist reminder mail with their wishlist. ... yeah, .... Not sure how to fix this but it happens too often.

**Comment by acrobat** [comment]
We could implement some logic so we parse replied mails. Same thing like github does, when you reply to a notification mail they add the reply as a comment in the issue/pr

**Comment by TomCan** [comment]
I think we should just ignore or bounce these emails. Parsing them and
forwarding them could easily expose the secret Santa (eg . signature).

Alternatively we could add functionality to communicate anonymously through
the site.

Tom
Op 19 dec. 2015 09:31 schreef "Jeroen Thora" <notifications@github.com>:

**Comment by tvlooy** [comment]
I ignored these mails for a long time but that is not ok. I added a default reply in Kayako now. Parsing is an option but very error prone.

**Comment by tvlooy** [comment]
won't fix. This is sent by no-reply with autoreply now
