### ISSUE TITLE
Data reporting

### ISSUE THREAD

**Issue by NielsRoels** [Intracto/SecretSanta#61]
Rebuild report to page to display useful information:

- Amount of pools that have been created
- Amount of people that are included in those pools
- Average amount of people that are included into a pool
- What country does the user live in? (in %)
- Which language does the user speak? (in %)
- How many of the created wishlists have been completed? (in %)
- Amount of emails that have been sent
- Amount of emails that have been opened
- Average time between receiving and opening a mail
- Mobile and desktop usage
- Top browsers

Make sure people can filter data by year/season. Try to cache data from previous years to prevent the usage of too many API calls.

**Comment by tvlooy** [comment]
@NielsRoels close en maak even nieuw issue met todo's
