### ISSUE TITLE
Invite (mailing) users of last year(s)

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#70]
People should know we have a new version. Thank them for their past use and invite them this year. We do this for free, the only reward we have is users actually using the thing. Discuss with EMA team because we don't want to become spammers of course.

**Comment by tvlooy** [comment]
TODO:
- CSV export email addresses for mailing
- 1 mailing to everyone to encourage people to start a new secretsanta

**Comment by hvanoch** [comment]
/export/entries downloads a csv export

**Comment by tvlooy** [comment]
@hvanoch
1) can you add an indication if the persons is the pool owner? We want to send different e-mails.
2) /export/entries returns 1 row in production :-) can you check?
3) if this is ready, send the page and credentials to Herman so he can do his thing

**Comment by hvanoch** [comment]
This is done.

**Comment by tvlooy** [comment]
super!! Thanks
