### ISSUE TITLE
Followup mail pool members

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#73]
Send an email after 2 weeks if they didn't watch their pair yet. But, do not mail after event date!

**Comment by jeroenmoons** [comment]
How many times should this reminder mail be sent? Just once or X times with Y days in between with a max of Z times, ...?

**Comment by tvlooy** [comment]
max 3x met periode van 2 weken tussen. Terug te tellen vanaf het event (laatste keer 2 weken voor event, 4 weken voor event en eerste keer 6 weken voor event)

**Comment by jeroenmoons** [comment]
Goed dit zit erin, idem voor issue 74 (volledig analoog). Ik wacht nog op franse vertalingen.

**Comment by tvlooy** [comment]
steek de vertalingen er nog maar in. Ik close issue alvast

**Comment by jeroenmoons** [comment]
Franse vertalingen voor dit issue zitten in master.
