### ISSUE TITLE
Remind wishlist

### ISSUE THREAD

**Issue by tvlooy** [Intracto/SecretSanta#74]
After 2 weeks send an email if they didn't add items to their wishlist. Do not email after event date!

**Comment by jeroenmoons** [comment]
Dit zit erin, analoog aan issue 73. Ik wacht nog op franse vertalingen.

**Comment by tvlooy** [comment]
steek de vertalingen er nog maar in. Ik close issue alvast

**Comment by jeroenmoons** [comment]
De franse vertalingen voor dit issue en #73 zijn toegevoegd en zitten in master.
