### ISSUE TITLE
Mailing

### ISSUE THREAD

**Issue by NielsRoels** [Intracto/SecretSanta#93]
- [x] Analysis of current state of mailing
- [x] Clean up existing code and rework/delete
- [ ] Improve mail content, make them more inviting
- [x] Add new mails (poke buddy, pool status, ...)
- [x] Automate certain mails

**Comment by tvlooy** [comment]
niet duidelijk wat we nog moeten doen. Reopen met concrete todo's

**Comment by alves94daniela** [comment]
Good afternoon, I created an event on the website https://www.secretsantaorganizer.com/pt
But I lost the email containing the link to manage the list.
Would it be possible to recover?

**Comment by TomCan** [comment]
Please read the FAQ before creating an issue, or responding to non-related issue.
https://www.secretsantaorganizer.com/en/faq
